### ISSUE TITLE
Implementing output

### ISSUE THREAD

**Issue by marvinboe** [marvinboe/TNBCABM#1]
We need to implement a nice output function to usable data. Any ideas?

**Comment by D3r3kPark** [comment]
I have a few ideas of how to display them. 

The way I understand it, our two primary variables are:

1) Proliferation rate
2) Antigenicity

I think that we are going to have histograms of each changing over time as well as a phase diagram. 

We don't have a lot of time so unfortunately we need to make the graphics a bit information dense. I can present and explain it, though, and think it should be fine.

**Comment by marvinboe** [comment]
We still have toy-values for proliferation rate and antigenicity...
I can send you a file with the actual proliferation/antigenicity values (two rows) later. Alternatively we could include the actual values in the first row/column of each data file, respectively. What do you prefer?

**Comment by D3r3kPark** [comment]
The 2D matrix is fine. I do need an X and Y range. I'll post some example figures shortly. Looks good!
